
export const statusClass = {
    'Under Approval': 'status-warning',
    'Approved': 'status-info',
    'Published': 'status-success',
    'Unpublished': 'status-secondary',
    'Rejected': 'status-danger',
    'suspended': 'status-danger',
    'pending': 'status-warning',
    'approved': 'status-info',
    'rejected': 'status-danger',
    'processing': 'status-info',
    'active': 'status-info',
    'completed': 'status-success',
    'complete': 'status-success',
    'cancelled': 'status-danger',
    'failed': 'status-danger',
    'refunded': 'status-danger',
    'on-hold': 'status-warning',
    'trash': 'status-info',
    'accepted': 'status-info',
    'started': 'status-success',
    'driver_pending': 'status-danger',
    'user_pending': 'status-danger',
    'ride': 'status-danger',
    'add_money': 'status-success',
    'paid': 'status-success',
    'break': 'status-warning',
}